In [63]:
import numpy as np
import pandas as pd

In [64]:
df = pd.read_csv('/content/diabetes.csv')

In [65]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [66]:
df.shape

(768, 9)

In [67]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.495990
BloodPressure               0.174469
SkinThickness               0.295138
Insulin                     0.377081
BMI                         0.315577
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [68]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [69]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_scaled = scalar.fit_transform(X)

In [70]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state =1)

In [71]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [72]:
from keras.src.metrics import metric
model = Sequential()
model.add(Dense(32,activation = 'relu',input_dim =8))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'Adam',loss ='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [73]:
model.fit(X_train,y_train,batch_size=32,epochs = 100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.5065 - loss: 0.7098 - val_accuracy: 0.6104 - val_loss: 0.6582
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6221 - loss: 0.6388 - val_accuracy: 0.6883 - val_loss: 0.5972
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6580 - loss: 0.5886 - val_accuracy: 0.7727 - val_loss: 0.5505
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6987 - loss: 0.5521 - val_accuracy: 0.7597 - val_loss: 0.5166
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7296 - loss: 0.5253 - val_accuracy: 0.7727 - val_loss: 0.4909
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7362 - loss: 0.5054 - val_accuracy: 0.7857 - val_loss: 0.4702
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7459 - loss: 0.4904 - val_accuracy: 0.7922 - val_loss: 0.4548
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7573 - loss: 0.4777 - val_accuracy: 0.7987 - val_loss: 0.4426
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7573 - loss: 0.4680 - val_accuracy: 0.7987 - val_loss: 0.4334
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.4597 - val_accuracy: 0.8052 - val_loss: 0.4243
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4527 - val_accuracy: 0.8312 - val_loss: 0.4182
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4466 - val_accuracy: 0.8312 - val_loss: 0.4127
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4420 - val_accuracy: 0.8247 - val_loss: 0.4086
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4371 - val_accuracy: 0.8247 - val_loss: 0.4043
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4321 - val_accuracy: 0.8312 - val_loss: 0.4000
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4282 - val_accuracy: 0.8247 - val_loss: 0.3960
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4243 - val_accuracy: 0.8377 - val_loss: 0.3923
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4208 - val_accuracy: 0.8442 - val_loss: 0.3890
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4168 - val_accuracy: 0.8506 - val_loss: 0.3860
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4135 - val_accuracy: 0.8442 - val_loss: 0.3832
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4101 - val_accuracy: 0.8442 - val_loss: 0.3801
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4070 - val_accuracy: 0.8442 - val_loss: 0.3776
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4038 - val_accuracy: 0.8506 - val_loss: 0.3754
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4008 - val_accuracy: 0.8377 - val_loss: 0.3743
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.3979 - val_accuracy: 0.8312 - val_loss: 0.3727
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3944 - val_accuracy: 0.8442 - val_loss: 0.3691
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3915 - val_accuracy: 0.8442 - val_loss: 0.3669
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.3886 - val_accuracy: 0.8377 - val_loss: 0.3650
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.3857 - val_accuracy: 0.8506 - val_loss: 0.3631
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3832 - val_accuracy: 0.8571 - val_loss: 0.3613
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3799 - val_accuracy: 0.8571 - val_loss: 0.3593
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3774 - val_accuracy: 0.8571 - val_loss: 0.3575
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3749 - val_accuracy: 0.8636 - val_loss: 0.3556
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3723 - val_accuracy: 0.8701 - val_loss: 0.3536
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3693 - val_accuracy: 0.8701 - val_loss: 0.3522
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3675 - val_accuracy: 0.8701 - val_loss: 0.3506
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3649 - val_accuracy: 0.8636 - val_loss: 0.3499
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3627 - val_accuracy: 0.8701 - val_loss: 0.3475
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3606 - val_accuracy: 0.8701 - val_loss: 0.3463
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3584 - val_accuracy: 0.8701 - val_loss: 0.3455
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3563 - val_accuracy: 0.8701 - val_loss: 0.3442
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3541 - val_accuracy: 0.8701 - val_loss: 0.3428
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3522 - val_accuracy: 0.8701 - val_loss: 0.3420
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8502 - loss: 0.3509 - val_accuracy: 0.8701 - val_loss: 0.3414
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3481 - val_accuracy: 0.8766 - val_loss: 0.3403
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3465 - val_accuracy: 0.8766 - val_loss: 0.3394
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8567 - loss: 0.3449 - val_accuracy: 0.8701 - val_loss: 0.3380
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8583 - loss: 0.3430 - val_accuracy: 0.8831 - val_loss: 0.3383
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3410 - val_accuracy: 0.8766 - val_loss: 0.3368
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8648 - loss: 0.3390 - val_accuracy: 0.8701 - val_loss: 0.3362
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8648 - loss: 0.3380 - val_accuracy: 0.8831 - val_loss: 0.3362
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3363 - val_accuracy: 0.8766 - val_loss: 0.3350
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8697 - loss: 0.3343 - val_accuracy: 0.8701 - val_loss: 0.3343
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8697 - loss: 0.3332 - val_accuracy: 0.8701 - val_loss: 0.3335
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8681 - loss: 0.3320 - val_accuracy: 0.8701 - val_loss: 0.3327
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8713 - loss: 0.3305 - val_accuracy: 0.8701 - val_loss: 0.3327
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8713 - loss: 0.3293 - val_accuracy: 0.8701 - val_loss: 0.3314
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3282 - val_accuracy: 0.8701 - val_loss: 0.3310
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8746 - loss: 0.3263 - val_accuracy: 0.8701 - val_loss: 0.3312
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3251 - val_accuracy: 0.8701 - val_loss: 0.3311
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3243 - val_accuracy: 0.8896 - val_loss: 0.3322
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.3230 - val_accuracy: 0.8961 - val_loss: 0.3336
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8827 - loss: 0.3224 - val_accuracy: 0.8896 - val_loss: 0.3317
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3217 - val_accuracy: 0.8896 - val_loss: 0.3321
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3206 - val_accuracy: 0.8896 - val_loss: 0.3329
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3195 - val_accuracy: 0.8896 - val_loss: 0.3331
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3186 - val_accuracy: 0.8831 - val_loss: 0.3319
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3179 - val_accuracy: 0.8896 - val_loss: 0.3300
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3171 - val_accuracy: 0.8896 - val_loss: 0.3298
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3165 - val_accuracy: 0.8831 - val_loss: 0.3297
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3154 - val_accuracy: 0.8896 - val_loss: 0.3296
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3150 - val_accuracy: 0.8766 - val_loss: 0.3301
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3143 - val_accuracy: 0.8701 - val_loss: 0.3308
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3138 - val_accuracy: 0.8766 - val_loss: 0.3311
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3129 - val_accuracy: 0.8701 - val_loss: 0.3308
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3124 - val_accuracy: 0.8701 - val_loss: 0.3292
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3120 - val_accuracy: 0.8831 - val_loss: 0.3294
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3121 - val_accuracy: 0.8701 - val_loss: 0.3292
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3107 - val_accuracy: 0.8701 - val_loss: 0.3299
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3101 - val_accuracy: 0.8701 - val_loss: 0.3302
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8827 - loss: 0.3098 - val_accuracy: 0.8766 - val_loss: 0.3308
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8860 - loss: 0.3095 - val_accuracy: 0.8766 - val_loss: 0.3296
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8876 - loss: 0.3086 - val_accuracy: 0.8766 - val_loss: 0.3305
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8827 - loss: 0.3084 - val_accuracy: 0.8766 - val_loss: 0.3313
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3078 - val_accuracy: 0.8766 - val_loss: 0.3312
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8844 - loss: 0.3072 - val_accuracy: 0.8766 - val_loss: 0.3306
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8827 - loss: 0.3069 - val_accuracy: 0.8766 - val_loss: 0.3302
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8844 - loss: 0.3066 - val_accuracy: 0.8766 - val_loss: 0.3297
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8844 - loss: 0.3059 - val_accuracy: 0.8766 - val_loss: 0.3303
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8827 - loss: 0.3058 - val_accuracy: 0.8766 - val_loss: 0.3310
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3058 - val_accuracy: 0.8766 - val_loss: 0.3343
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3053 - val_accuracy: 0.8766 - val_loss: 0.3323
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3048 - val_accuracy: 0.8766 - val_loss: 0.3330
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3044 - val_accuracy: 0.8766 - val_loss: 0.3330
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3039 - val_accuracy: 0.8766 - val_loss: 0.3330
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3035 - val_accuracy: 0.8766 - val_loss: 0.3325
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3032 - val_accuracy: 0.8766 - val_loss: 0.3315
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3026 - val_accuracy: 0.8766 - val_loss: 0.3301
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.3022 - val_accuracy: 0.8766 - val_loss: 0.3306
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3015 - val_accuracy: 0.8831 - val_loss: 0.3291

In [74]:
pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.13/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.83.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [75]:
import keras_tuner as kt

In [96]:
def build_model(hp):
  model = Sequential()
  count =0
  for i in range(hp.Int('num_layers',min_value=1,max_value=8)):
    if count == 0:
      model.add(Dense(hp.Int('units' + str(i),min_value=32,max_value =128,step=8),
                      activation = hp.Choice('activation' + str(i),values = ['relu','tanh']),input_dim = 8))
      model.add(Dropout(hp.Choice('dropout'+str(i),values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(Dense(hp.Int('units' + str(i),min_value=32,max_value =128,step=8),
                      activation = hp.Choice('activation' + str(i),values = ['relu','tanh'])))
      model.add(Dropout(hp.Choice('dropout'+str(i),values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    count += 1

  model.add(Dense(1,activation ='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['rmsprop','adam','sgd','adadelta','nadam']),loss= 'binary_crossentropy',metrics=['accuracy'])
  return model

In [97]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',project_name='_rekon')

In [98]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 16s

In [100]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units0': 32,
 'activation0': 'relu',
 'dropout0': 0.1,
 'optimizer': 'sgd',
 'units1': 32,
 'activation1': 'tanh',
 'dropout1': 0.1,
 'units2': 56,
 'activation2': 'relu',
 'dropout2': 0.4,
 'units3': 80,
 'activation3': 'tanh',
 'dropout3': 0.1}

In [101]:
model = tuner.get_best_models(num_models=1)[0]

In [102]:
model.fit(X_train,y_train,epochs=200,initial_epoch =6,validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6824 - loss: 0.6101 - val_accuracy: 0.7857 - val_loss: 0.5763
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7085 - loss: 0.5919 - val_accuracy: 0.7792 - val_loss: 0.5595
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.5877 - val_accuracy: 0.7727 - val_loss: 0.5453
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7117 - loss: 0.5687 - val_accuracy: 0.7727 - val_loss: 0.5331
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7215 - loss: 0.5495 - val_accuracy: 0.7727 - val_loss: 0.5218
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7427 - loss: 0.5426 - val_accuracy: 0.7792 - val_loss: 0.5110
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7280 - loss: 0.5464 - val_accuracy: 0.7857 - val_loss: 0.5033
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5333 - val_accuracy: 0.7987 - val_loss: 0.4949
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7476 - loss: 0.5263 - val_accuracy: 0.7987 - val_loss: 0.4876
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5281 - val_accuracy: 0.8117 - val_loss: 0.4814
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5180 - val_accuracy: 0.8117 - val_loss: 0.4760
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5054 - val_accuracy: 0.8117 - val_loss: 0.4710
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5256 - val_accuracy: 0.8117 - val_loss: 0.4673
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5137 - val_accuracy: 0.8117 - val_loss: 0.4640
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4958 - val_accuracy: 0.8247 - val_loss: 0.4595
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5097 - val_accuracy: 0.8247 - val_loss: 0.4559
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7541 - loss: 0.5123 - val_accuracy: 0.8247 - val_loss: 0.4525
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4969 - val_accuracy: 0.8182 - val_loss: 0.4485
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7590 - loss: 0.5019 - val_accuracy: 0.8182 - val_loss: 0.4455
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7524 - loss: 0.5018 - val_accuracy: 0.8182 - val_loss: 0.4441
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7606 - loss: 0.4942 - val_accuracy: 0.8182 - val_loss: 0.4412
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4797 - val_accuracy: 0.8182 - val_loss: 0.4388
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4857 - val_accuracy: 0.8182 - val_loss: 0.4364
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7736 - loss: 0.4794 - val_accuracy: 0.8247 - val_loss: 0.4335
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7687 - loss: 0.4790 - val_accuracy: 0.8247 - val_loss: 0.4309
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4762 - val_accuracy: 0.8312 - val_loss: 0.4288
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4752 - val_accuracy: 0.8312 - val_loss: 0.4271
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4810 - val_accuracy: 0.8312 - val_loss: 0.4260
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4846 - val_accuracy: 0.8247 - val_loss: 0.4247
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4594 - val_accuracy: 0.8247 - val_loss: 0.4229
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4829 - val_accuracy: 0.8312 - val_loss: 0.4216
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4677 - val_accuracy: 0.8312 - val_loss: 0.4199
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4584 - val_accuracy: 0.8182 - val_loss: 0.4185
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4655 - val_accuracy: 0.8247 - val_loss: 0.4167
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4607 - val_accuracy: 0.8182 - val_loss: 0.4150
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4528 - val_accuracy: 0.8247 - val_loss: 0.4135
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4742 - val_accuracy: 0.8182 - val_loss: 0.4128
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4606 - val_accuracy: 0.8182 - val_loss: 0.4115
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4509 - val_accuracy: 0.8247 - val_loss: 0.4100
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4601 - val_accuracy: 0.8312 - val_loss: 0.4090
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4649 - val_accuracy: 0.8247 - val_loss: 0.4085
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4562 - val_accuracy: 0.8182 - val_loss: 0.4078
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4536 - val_accuracy: 0.8247 - val_loss: 0.4074
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4673 - val_accuracy: 0.8312 - val_loss: 0.4064
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4431 - val_accuracy: 0.8247 - val_loss: 0.4065
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4582 - val_accuracy: 0.8247 - val_loss: 0.4052
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4436 - val_accuracy: 0.8247 - val_loss: 0.4042
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4545 - val_accuracy: 0.8247 - val_loss: 0.4032
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4521 - val_accuracy: 0.8247 - val_loss: 0.4028
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4442 - val_accuracy: 0.8247 - val_loss: 0.4019
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4361 - val_accuracy: 0.8182 - val_loss: 0.4009
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4459 - val_accuracy: 0.8247 - val_loss: 0.3997
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4568 - val_accuracy: 0.8312 - val_loss: 0.3989
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4494 - val_accuracy: 0.8247 - val_loss: 0.3996
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4541 - val_accuracy: 0.8247 - val_loss: 0.3988
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4374 - val_accuracy: 0.8312 - val_loss: 0.3979
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4485 - val_accuracy: 0.8312 - val_loss: 0.3974
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4244 - val_accuracy: 0.8377 - val_loss: 0.3959
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4314 - val_accuracy: 0.8377 - val_loss: 0.3953
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4305 - val_accuracy: 0.8377 - val_loss: 0.3950
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4355 - val_accuracy: 0.8442 - val_loss: 0.3938
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4344 - val_accuracy: 0.8442 - val_loss: 0.3930
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4240 - val_accuracy: 0.8442 - val_loss: 0.3917
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4270 - val_accuracy: 0.8442 - val_loss: 0.3905
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4406 - val_accuracy: 0.8442 - val_loss: 0.3903
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4291 - val_accuracy: 0.8442 - val_loss: 0.3897
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4235 - val_accuracy: 0.8442 - val_loss: 0.3893
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.4126 - val_accuracy: 0.8442 - val_loss: 0.3877
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4259 - val_accuracy: 0.8377 - val_loss: 0.3874
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4281 - val_accuracy: 0.8442 - val_loss: 0.3869
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4282 - val_accuracy: 0.8377 - val_loss: 0.3859
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4021 - val_accuracy: 0.8377 - val_loss: 0.3851
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4317 - val_accuracy: 0.8377 - val_loss: 0.3844
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4188 - val_accuracy: 0.8377 - val_loss: 0.3835
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4157 - val_accuracy: 0.8377 - val_loss: 0.3824
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4172 - val_accuracy: 0.8377 - val_loss: 0.3816
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4388 - val_accuracy: 0.8442 - val_loss: 0.3821
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4210 - val_accuracy: 0.8312 - val_loss: 0.3810
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4117 - val_accuracy: 0.8442 - val_loss: 0.3798
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4151 - val_accuracy: 0.8442 - val_loss: 0.3796
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4015 - val_accuracy: 0.8442 - val_loss: 0.3783
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4212 - val_accuracy: 0.8442 - val_loss: 0.3781
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4250 - val_accuracy: 0.8442 - val_loss: 0.3776
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4102 - val_accuracy: 0.8442 - val_loss: 0.3768
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4005 - val_accuracy: 0.8442 - val_loss: 0.3762
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4137 - val_accuracy: 0.8442 - val_loss: 0.3760
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4196 - val_accuracy: 0.8442 - val_loss: 0.3759
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4180 - val_accuracy: 0.8442 - val_loss: 0.3755
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4192 - val_accuracy: 0.8442 - val_loss: 0.3751
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4254 - val_accuracy: 0.8442 - val_loss: 0.3763
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4079 - val_accuracy: 0.8442 - val_loss: 0.3751
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4157 - val_accuracy: 0.8442 - val_loss: 0.3740
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4125 - val_accuracy: 0.8442 - val_loss: 0.3733
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3986 - val_accuracy: 0.8442 - val_loss: 0.3725
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4048 - val_accuracy: 0.8377 - val_loss: 0.3722
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4090 - val_accuracy: 0.8442 - val_loss: 0.3717
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4042 - val_accuracy: 0.8442 - val_loss: 0.3714
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4131 - val_accuracy: 0.8506 - val_loss: 0.3707
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4069 - val_accuracy: 0.8442 - val_loss: 0.3711
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4147 - val_accuracy: 0.8377 - val_loss: 0.3700
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4047 - val_accuracy: 0.8442 - val_loss: 0.3697
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3996 - val_accuracy: 0.8442 - val_loss: 0.3683
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.4028 - val_accuracy: 0.8442 - val_loss: 0.3681
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8355 - loss: 0.3970 - val_accuracy: 0.8442 - val_loss: 0.3671
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.3804 - val_accuracy: 0.8442 - val_loss: 0.3664
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.3974 - val_accuracy: 0.8442 - val_loss: 0.3662
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.3807 - val_accuracy: 0.8442 - val_loss: 0.3656
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4043 - val_accuracy: 0.8442 - val_loss: 0.3666
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8225 - loss: 0.3874 - val_accuracy: 0.8442 - val_loss: 0.3657
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8371 - loss: 0.3839 - val_accuracy: 0.8442 - val_loss: 0.3650
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8013 - loss: 0.3968 - val_accuracy: 0.8442 - val_loss: 0.3645
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8274 - loss: 0.3937 - val_accuracy: 0.8442 - val_loss: 0.3640
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4043 - val_accuracy: 0.8442 - val_loss: 0.3634
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4067 - val_accuracy: 0.8442 - val_loss: 0.3630
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3899 - val_accuracy: 0.8442 - val_loss: 0.3627
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4059 - val_accuracy: 0.8442 - val_loss: 0.3627
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3856 - val_accuracy: 0.8442 - val_loss: 0.3618
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3840 - val_accuracy: 0.8442 - val_loss: 0.3614
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3853 - val_accuracy: 0.8442 - val_loss: 0.3609
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3965 - val_accuracy: 0.8442 - val_loss: 0.3602
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4122 - val_accuracy: 0.8442 - val_loss: 0.3613
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.3902 - val_accuracy: 0.8442 - val_loss: 0.3611
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3822 - val_accuracy: 0.8442 - val_loss: 0.3611
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3750 - val_accuracy: 0.8442 - val_loss: 0.3602
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3870 - val_accuracy: 0.8506 - val_loss: 0.3605
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3910 - val_accuracy: 0.8506 - val_loss: 0.3598
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3900 - val_accuracy: 0.8506 - val_loss: 0.3595
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3893 - val_accuracy: 0.8506 - val_loss: 0.3595
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3883 - val_accuracy: 0.8506 - val_loss: 0.3580
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3717 - val_accuracy: 0.8506 - val_loss: 0.3567
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3792 - val_accuracy: 0.8506 - val_loss: 0.3556
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3804 - val_accuracy: 0.8506 - val_loss: 0.3547
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3794 - val_accuracy: 0.8506 - val_loss: 0.3540
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3828 - val_accuracy: 0.8506 - val_loss: 0.3534
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3841 - val_accuracy: 0.8506 - val_loss: 0.3530
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3761 - val_accuracy: 0.8506 - val_loss: 0.3524
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3995 - val_accuracy: 0.8506 - val_loss: 0.3522
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3778 - val_accuracy: 0.8506 - val_loss: 0.3517
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3643 - val_accuracy: 0.8506 - val_loss: 0.3512
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3648 - val_accuracy: 0.8506 - val_loss: 0.3511
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3819 - val_accuracy: 0.8506 - val_loss: 0.3508
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3808 - val_accuracy: 0.8506 - val_loss: 0.3505
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3597 - val_accuracy: 0.8506 - val_loss: 0.3495
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8322 - loss: 0.3862 - val_accuracy: 0.8506 - val_loss: 0.3491
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3711 - val_accuracy: 0.8571 - val_loss: 0.3487
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3615 - val_accuracy: 0.8571 - val_loss: 0.3490
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3852 - val_accuracy: 0.8571 - val_loss: 0.3486
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8502 - loss: 0.3670 - val_accuracy: 0.8571 - val_loss: 0.3478
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3578 - val_accuracy: 0.8571 - val_loss: 0.3469
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3777 - val_accuracy: 0.8701 - val_loss: 0.3470
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3573 - val_accuracy: 0.8636 - val_loss: 0.3483
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3721 - val_accuracy: 0.8636 - val_loss: 0.3479
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3767 - val_accuracy: 0.8636 - val_loss: 0.3475
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3755 - val_accuracy: 0.8636 - val_loss: 0.3473
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3660 - val_accuracy: 0.8636 - val_loss: 0.3461
Epoch 162/200